### ISSUE TITLE
assert(floor_thread_key != 0x7777) fails in coroutine.cc line 49

### ISSUE THREAD

**Issue by garytaylor** [laverdet/node-fibers#179]
When installing fibers 1.0.1, I get the following on 2 windows machines tested (both 64 bit Windows 7 Enterprise with quad core and 32GB of RAM) :

Assertion failed!
Program:...e_modules\fibers\bin\win32-x64-v8-3.14\fibers.node
File: ..\src\coroutine.cc
Line: 49

Expression: floor_thread_key != 0

Ticket #122 was raised for this, but it looks like it was never resolved.
I am struggling with any of the solutions offered in that ticket, any help would be greatly appreciated

**Comment by laverdet** [comment]
Yeah I had to unpublish 1.0.3 because it introduced some other issues. 1.0.4 is in npm now which should have the fixes.

**Comment by xmojmr** [comment]
@laverdet the problem persists even after `npm cache clear` and `npm update` to the correct `fibers@1.0.4`.

It seems that this is a new problem and everything was just fine with node v0.10.33 and fibers-nodejs 1.0.1.

Do you have any troubleshooting guidelines ?

**Comment by laverdet** [comment]
@xmojmr can you give more detailed information about your operating system, version of node, and the script you're running and how it fails?

**Comment by xmojmr** [comment]
I have two virtual machines `A` and `B`. `A` is just fine.

Configuration of `A`:

tag | value     
-----|--------
OS version | Windows 7 Home Premium 32-bit
`node --version` | v0.10.35
`npm list node-gyp -g` | version 0.10.13
C++ compiler| Visual Studio 2013

Configuration of `B`:

tag | value
-----|-------
OS version | Windows XP Professional 2002 SP3 32-bit
`node --version`| v0.10.35
`npm list node-gyp -g`| version 1.0.2
C++ compiler| Visual Studio 2010 Express

During installation of the `fibers` package on the machine `B` this appears on the screen
```
'win32-ia32-v8-3.14' exists; testing
Problem with the binary; manual build incoming
```
and build script is triggered creating file `node_modules\fibers\bin\win32-x64-v8-3.14\fibers.node` (and quite a few yellow warnings).

Running `npm test` in the `node_modules\fibers` folder says all tests **passed**.

However, this `error.js` script:
```
console.log("1");
var Fiber = require('fibers');
console.log("2");
```

produces this output:

![image](https://cloud.githubusercontent.com/assets/6378964/5627433/1bfa7b32-9598-11e4-92ae-c71c0f15a681.png)

expected output would be:
```
1
2
```

As a **workaround** I can resolve it by manually copying file `...\win32-x64-v8-3.14\fibers.node` from machine `A` (where it both compiles and runs fine) to machine `B`. The `fibers.node` binary compiled on machine `A` is fortunately compatible with machine `B`.

Do you have any further troubleshooting instructions ?

**Comment by laverdet** [comment]
I've received other reports of fibers not working correctly on Windows XP. I don't really care to support Windows XP since it's over a decade old and not even supported by Microsoft anymore. Patches are welcome if you want to look into it yourself though.

**Comment by xmojmr** [comment]
@laverdet ok, I'll then rollback my dependencies back to the stable `fibers` version. Everything was fine a few months ago so the stable XP-compatible version must exist :wink:

I won't dive into the problem myself as on the XP machine I don't have C++ development tools available (no JIT debugger to name one).

Thanks for you assistance, IO: what was the root cause of this issue?

**Comment by laverdet** [comment]
Interesting. Can you pinpoint why 1.0.1 worked but 1.0.5 doesn't? 1.0.1 only scans the last 20 tls slots as well.

**Comment by xmojmr** [comment]
@laverdet it turned out on the 1 Windows XP virtual machine that I used for testing, that even rollback to `fibers@1.0.1in further testing that on the 1 Windows XP machine I used the `fibers@1.0.1` 

![image](https://cloud.githubusercontent.com/assets/6378964/5658476/99a64686-9702-11e4-9671-182ccd129d4d.png)

![image](https://cloud.githubusercontent.com/assets/6378964/5658468/78656eb6-9702-11e4-9e66-3ab80cb3ba2c.png)

**Comment by laverdet** [comment]
20 was just a random number. v8 itself registers 3 tls keys and I hadn't seen any cases where extra keys are allocated in the mean time so it didn't seem like it would need to be very high. In the case of OS X, I noticed that v8 doesn't get to register tls keys until there's 300-400 already registered and I was worried that starting from 0 on platforms like that it would take a long time to initialize.

I can bump the limit up, but I am wondering where all those extra keys are going.

**Comment by xmojmr** [comment]
I tried to inspect it little bit more but I can't get the exact list of `TlsAlloc` callers as on the Windows XP box I don't have the development tools needed. Some result of the tests:

test run | coro_thread_key | isolate_key | coro_thread_key - isolate_key
----------|-----------------------|----------------|--------------------------------------
tr1|32|10|22
tr2|15|10|5
tr3|32|10|22
tr4|32|8|24
tr5|29|8|21

The numbers differ because different test runs had different environment conditions, e.g. the number of hook DLLs attached to them by various tools (I don't have them written down so some of the tests are not repeatable)

Sample `TLS` dump corresponding to the **tr4**:

```
00000041	1182.10559082	[4748] tls[8]: 0x3f52c8	
00000042	1182.10571289	[4748] tls[9]: 0x2	
00000043	1182.10583496	[4748] tls[10]: 0xf447a8	
00000044	1182.10583496	[4748] tls[11]: 0x0	
00000045	1182.10595703	[4748] tls[12]: 0x0	
00000046	1182.28686523	[4748] tls[13]: 0x0	
00000047	1182.28710938	[4748] tls[14]: 0x0	
00000048	1182.28723145	[4748] tls[15]: 0x0	
00000049	1182.28735352	[4748] tls[16]: 0x0	
00000050	1182.28747559	[4748] tls[17]: 0x0	
00000051	1182.28759766	[4748] tls[18]: 0x0	
00000052	1182.38171387	[4748] tls[20]: 0x0	
00000053	1182.38256836	[4748] tls[21]: 0x0	
00000054	1182.38269043	[4748] tls[22]: 0x0	
00000055	1182.38293457	[4748] tls[23]: 0x17c530	
00000056	1182.38317871	[4748] tls[24]: 0x0	
00000057	1182.38342285	[4748] tls[25]: 0x0	
00000058	1182.38354492	[4748] tls[26]: 0x0	
00000059	1182.38378906	[4748] tls[27]: 0x7c8097e0	
00000060	1182.38403320	[4748] tls[28]: 0x1ec3e68	
00000061	1182.38427734	[4748] tls[29]: 0x0	
00000062	1182.38439941	[4748] tls[30]: 0x7c8097e0	
00000063	1182.48547363	[4748] tls[31]: 0x65c4698	
```

We know that by examining http://svn.reactos.org/svn/reactos/trunk/reactos/dll/win32/kernel32/client/thread.c?view=markup it seems that the valid ThreadLocalStorage index range is `0...TLS_EXPANSION_SLOTS + TLS_MINIMUM_AVAILABLE - 1` and OS assigns the TLS indexes by one by one (**reusing old index** if it was `TlsFree`-d in the meantime).

So if the OS (or whoever) loads a DLL `A` into `node.js` process and the DLL allocates TLS slot with index `2` and later a background thread spawned by the DLL `A` terminates and releases the TLS slot index `2` then a DLL `B` which was loaded later may get the value `2` as a result of it's own TLS slot allocation call. Given that there are also other DLLs running and allocating and releasing TLS slots the **ordering** of TLS indexes is **not well defined**. Distance between two TLS slot indexes does not represent the number of `TlsAlloc` calls between the points when the slots were allocated.

So the new hypothesis is that by replacing:

<del><code>for (pthread_key_t ii = (coro_thread_key >= 20 ? coro_thread_key - 20 : 0); ii &lt; coro_thread_key; ++ii)</code></del>

<br>With:

<code>for (pthread_key_t ii = coro_thread_key - 1; ii >= 0; ii--)</code>

we might also solve the problem and the look-back window size guarded by the magic number could be left unlimited with no performance hit

---

BTW: my pull request will not compile on `#ifndef WINDOWS` platforms due to the use of `TLS_MINIMUM_AVAILABLE` constant

**Comment by laverdet** [comment]
Other OS's reuse TLS keys as well, but it doesn't seem to be a problem except on Windows XP. Searching the whole TLS space every time is problematic because in order to get `thread_data_key` we need to dereference a maybe-pointer, and we can only do that safely on Windows (see `can_poke`).

**Comment by xmojmr** [comment]
@laverdet the `for (pthread_key_t ii = coro_thread_key - 1; ii >= 0; ii--)` in the `isolate_key` search loop would probe TLS slots at

`coro_thread_key - 1`
`coro_thread_key - 2`
`coro_thread_key - 3`
`...`
`3`
`2`
`1`
`0`

and then fail.

If I understand the original loop correctly it was probing for TLS slots at

`coro_thread_key - 20`
`coro_thread_key - 19`
`coro_thread_key - 18`
`...`
`coro_thread_key - 1`

and then fail.

The only difference would be the direction. Both cases assume the the TLS slot value `isolate` is unique in the scanned range. And both cases don't include any kind of fancy error recovery (e.g. by trying to find a better `isolate_key` in case that the `thread_data_key` search would fail).

The `thread_data_key` code would remain the same, including the chance that it may fail.

So it should do no harm to other cases and resolve the case when the distance between `isolate_key` and `coro_thread_key` is above the magic 20.

Sure having some clear API for this purpose built on the `node.js` side (at least something like [.NET Thread.GetNamedDataSlot Method](http://referencesource.microsoft.com/#q=getnameddataslot)) would be better.

Using magic 30 as was proposed in https://github.com/laverdet/node-fibers/issues/122#issuecomment-36437883 would be also fine.

Saying you people with legacy Windows XP machines you're unsupported looks like the worst solution.

**Comment by laverdet** [comment]
Changing the 20 -> 30 won't fix it because the loops assume the keys are in order, but your Windows XP machine is generating keys out of order. You'll have to implement a more sophisticated fallback search that assumes nothing.

Windows XP has been officially *end-of-life* for almost a year now. Not supporting it is just as good a solution as not supporting Windows 98 or Windows ME. I'll accept a patch if I can be assured it won't break any other platforms, but I'm not putting the effort in myself. I think that's fair.
