### ISSUE TITLE
Version 1.0.7 in npm

### ISSUE THREAD

**Issue by vjchem** [laverdet/node-fibers#244]
We were pointing at fibers 1.0.6 in npm, but it seems that that version has beed removed and 1.0.7 is the latest. However, I don't see a version 1.0.7 in any of the branches here. Are there some commits that haven't been pushed it to github yet?

**Comment by laverdet** [comment]
I unpublished it because you used to be able to unpublish and republish a module to npm, but that changed a while back. So 1.0.6 is gone forever. 1.0.7 is identical to 1.0.6 with the exception of the binaries for node 0.10.x on Windows. See #236 for that discussion.

Leaving this open in case other people come here looking for answers.

**Comment by vjchem** [comment]
Ah, ok. Thanks for the quick response!
