### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by rogovdm** [laverdet/node-fibers#295]
npm ERR! Linux 4.4.14-moby
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--production"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.

**Comment by amilajack** [comment]
Have you tried `npm rb`?

**Comment by nickdandakis** [comment]
This is failing for me too. System info is:
Linux 4.1.19-v7+ armv7l
node v6.3.1
npm v3.10.5

Specifically, I'm trying to build this on a Raspberry Pi.

**Comment by laverdet** [comment]
`node` is not in your path or something.

**Comment by nickdandakis** [comment]
@laverdet, `node` was in my PATH.

The actual issue was that my version of `gcc` and `g++` was outdated. `build.js` tells you to `sudo apt-get install g++` which isn't terribly helpful if you don't know what version of g++ this requires.

Building native modules for Node requires:
- `gcc` and `g++` 4.8 or newer, or
- `clang` and `clang++` 3.4 or newer
- Python 2.6 or 2.7
- GNU Make 3.81 or newer

Raspberry Pi Wheezy has a version of `g++` that's less than 4.8. Update to Jessie for anyone running into this, or force install `g++ `4.8+
