### ISSUE TITLE
What is the ideal model for running node-fibers with express js

### ISSUE THREAD

**Issue by r-tock** [laverdet/node-fibers#296]
Do we start one fiber per request? Wondering if there are any known projects which show correct usage of node-fibers with a http server library like expressjs, Known gotcha's etc.

**Comment by veselov** [comment]
Yes to one fiber per request. Since request will come without a fiber, the first thing you do is wrap it into one, there really isn't a choice. 

The gotchas will be mainly in properly using futures as request is being processed, making sure you don't finish the request prematurely. There is a good amount of gotchas in error handling too, making sure you pass your errors to futures. 

Sometimes, it will nearly impossible to protect some futures from being resolved more than once, at least in my experience, I gave up on that, and just built a subclass that allows being resolved multiple times.

**Comment by r-tock** [comment]
Do you have such an example public? If not maybe put it as a example for this project?

**Comment by laverdet** [comment]
One fiber per request is the way most people do it. The easiest way to accomplish this is with `Future.task` in your http request handler.

Although I do urge you to check out [Koa](https://github.com/koajs/koa) instead of Express. I believe Koa will be the successor to both Fibers and Express in the years to come. Fibers can be adapted very easily to Koa w/Promise via `future.promise()` and `Future.fromPromise(...)`. Though for new applications I would honestly recommend starting with purely async+await over Fibers.

**Comment by bjouhier** [comment]
> Though for new applications I would honestly recommend starting with purely async+await over Fibers.

Fibers has nevertheless some advantages (\*):

- Leaner code: `async`/`await` is just noise, at least in _business logic_ layers. Fibers lets you write async code without extra syntax nor invasive API.
- More efficient code: calls within a coroutine are just vanilla JS function calls. Not sure that JS engine will be able to optimize async/await calls that far (but I may turn out wrong here). This is important if intra-coroutine calls dominate.
- Natural _continuation local storage_ (`Fiber.current`).
- _Normal_ stack traces.

(\*) Here I'm assuming that code is written in coroutine style (like in go): low level callback/promise apis are wrapped to be callable directly from a fiber; there is no attempt to keep the yielding points explicit everywhere in the code (no indirection through `.future()` /` .wait()` everywhere in the code).

The more I develop with node, the more I'm convinced that coroutines are a winner. So much simpler and cleaner than the callback/promise approaches (even with `async`/`await`). Disappointing to see that they have been around for more than 5 years and that we still are where we are.
