### ISSUE TITLE
Can't seem to install NativeScript

### ISSUE THREAD

**Issue by Billmike** [laverdet/node-fibers#336]
Attached is the error log file. Can someone please help me out!!! Thanks!!

[Error log file.docx](https://github.com/laverdet/node-fibers/files/827944/Error.log.file.docx)

**Comment by sjmcdowall** [comment]
I will hazard a guess here — although not official.  However, it appears you are using Node V7.X.  Fibers doesn’t come pre-compiled for “odd” # versions because those are “beta” versions — so NPM is looking to build fibers from scratch for you.  However, you don’t have the C++ environment setup to build it.  

Options:

1 — Use a node V6 version or wait until V8 if you MUST use the cool things added to V7 that will be LTS in V8 (in about 1-2 months)

2 — Setup a complete compile environment (see other issues here and maybe read the README) for your Windows platform.  

Good luck

**Comment by laverdet** [comment]
^
