### ISSUE TITLE
npm ERR! Failed at the fibers@2.0.2 install script.

### ISSUE THREAD

**Issue by lenagasilina** [laverdet/node-fibers#378]
Error on 

`npm i wdio-sync`

`npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@2.0.2 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by nex3** [comment]
I'm seeing this as well when installing fibers on Node 10.2.0. I'm getting this output:

```
  > fibers@2.0.2 install /home/travis/build/sass/dart-sass/node_modules/fibers
  > node build.js || nodejs build.js
  
  make: Entering directory `/home/travis/build/sass/dart-sass/node_modules/fibers/build'
    CXX(target) Release/obj.target/fibers/src/fibers.o
  make: Leaving directory `/home/travis/build/sass/dart-sass/node_modules/fibers/build'
  In file included from ../src/coroutine.h:1:0,
                   from ../src/fibers.cc:1:
  /home/travis/.node-gyp/10.2.0/include/node/node.h:53:50: fatal error: core.h: No such file or directory
   #include "core.h"  // NOLINT(build/include_order)
                                                    ^
  compilation terminated.
  make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
  gyp ERR! build error 
  gyp ERR! stack Error: `make` failed with exit code: 2
  gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v10.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
  gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
  gyp ERR! System Linux 4.14.12-041412-generic
  gyp ERR! command "/home/travis/.nvm/versions/node/v10.2.0/bin/node" "/home/travis/.nvm/versions/node/v10.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
  gyp ERR! cwd /home/travis/build/sass/dart-sass/node_modules/fibers
  gyp ERR! node -v v10.2.0
  gyp ERR! node-gyp -v v3.6.2
  gyp ERR! not ok 
  node-gyp exited with code: 1
  Please make sure you are using a supported platform and node version. If you
  would like to compile fibers on this machine please make sure you have setup your
  build environment--
  Windows + OS X instructions here: https://github.com/nodejs/node-gyp
  Ubuntu users please run: `sudo apt-get install g++ build-essential`
  Alpine users please run: `sudo apk add python make g++`
  sh: 1: nodejs: not found
  npm WARN dart-sass No repository field.
  npm WARN dart-sass No license field.
  
  npm ERR! file sh
  npm ERR! code ELIFECYCLE
  npm ERR! errno ENOENT
  npm ERR! syscall spawn
  npm ERR! fibers@2.0.2 install: `node build.js || nodejs build.js`
  npm ERR! spawn ENOENT
  npm ERR! 
  npm ERR! Failed at the fibers@2.0.2 install script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /home/travis/.npm/_logs/2018-05-24T16_25_20_578Z-debug.log
```

It seems that compilation was working as of Node 10.1.0.

**Comment by miguelsantos500** [comment]
Tried installing with v10.1.0, still can't install...

`
# node -v
v10.1.0
# npm i

> fibers@2.0.2 install /home/.../node_modules/fibers
> node build.js || nodejs build.js

sh: node: command not found
sh: nodejs: command not found
npm WARN sdp_testing@1.0.0 No description
npm WARN sdp_testing@1.0.0 No repository field.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@2.0.2 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-12T08_28_05_710Z-debug.log

`

**Comment by 171563857** [comment]
![image](https://user-images.githubusercontent.com/22027896/42261778-dbe2b5b8-7f9b-11e8-9a99-ce029a8a0249.png)
u node version is too lastest

**Comment by ruaneg** [comment]
anybody with an idea to get around this?

**Comment by catdad** [comment]
I am able to successfully install and use fibers with node 10.7.0 under Ubuntu (16?) and Windows 10, provided I have correctly set up node-gyp to work in both environments. I am not sure if the problem here are earlier versions of node or misconfigured node-gyp (as the rest of my team can't seem to set up node-gyp either).

Instead, a better question might be when will fibers ship with a prebuilt binary for module version 64?

**Comment by ywangii** [comment]
@catdad I got the same issue when using node@8. Is there any specific configuration stuff we need to notice to make it work? Thanks!

**Comment by catdad** [comment]
@ywangii Seems the errors being listed here are all errors with not having gyp configured quite right. You should be able to follow the steps here for your operating system: https://github.com/nodejs/node-gyp

One you do that, check if you can compile other modules. For example, can you install `nan` successfully?

I actually don't see why you would see such errors with node 8, considering that this module comes with pre-built binaries for node 8.

(Note: I don't actually maintain or know much about this particular module... I am just a random citizen that stumbled across this.)

**Comment by laverdet** [comment]
@nex3 I just published 3.0.0 on npm which has precompiled binaries for node 10.x, so that should help you out.

@lenagasilina @ywangii if you post a complete log and more information about your system (os version, cpu architecture, node version, etc) I might be able to help you out. npm has had precompiled binaries for 8.x for a very long time but something is preventing you from using them.

**Comment by ywangii** [comment]
@laverdet yea information is as below:

- Ubuntu 14.04.5
- node 8.11.3
- npm 6.2.0

The script gave me the `fibers` script error is `npm install --scripts-prepend-node-path` when running on the Ubuntu container. I have Dockerfile install `node-gyp`, `build-essential` etc.

```
RUN apt-get update -y
RUN apt-get install -y git bash g++ build-essential python2.7

RUN npm install -g node-gyp@3.6
```

The error looks like this:

```
sh: No such file or directory
node-gyp exited with code: 127

npm ERR! file /bin/bash
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@2.0.2 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Thanks for any thoughts and suggestions!

**Comment by laverdet** [comment]
What does `which node` output?

**Comment by nex3** [comment]
Thanks @laverdet!

**Comment by laverdet** [comment]
@ywangii how did you install nodejs on this server? nvm?

There is something wrong with the way your nodejs installation is set up. The installation script isn't even getting a chance to run.

**Comment by ywangii** [comment]
@laverdet This is the base image we are using currently for `apt-get` installing node. https://github.com/jcrugzz/s6-node-ubuntu/blob/master/Dockerfile#L5

**Comment by laverdet** [comment]
@ywangii the script you linked clearly installs nodejs 4.x but you're telling me that you're running nodejs 8.x. I think you're going to have to do some more troubleshooting on your own. I'm sorry I can't help you any further but this doesn't seem to be an issue with fibers.

**Comment by trentsteel777** [comment]
I was trying to run `sudo npx install-peerdeps --dev @reactioncommerce/eslint-config` and was seeing this error, the steps I took to fix were:
1. `sudo su - root`
2. `rm -rf ~/.node-gyp/`
3. `echo "alias node=\"meteor node\"" >> ~/.bash_aliases`
4. `source ~/.bash_aliases`
5. `sudo npx install-peerdeps --dev @reactioncommerce/eslint-config`

fibers successfully built for me then.

I had to switch to root user because npm install was throwing a permission error when trying to write to '../node_modules/fibers/build'. The idea for this came from here: https://github.com/gdotdesign/elm-github-install/issues/21#issuecomment-357460264

My installation of node is v11 so by creating the alias in .bash_aliases (in both root and my own user) I effectively downgraded my version of node to what meteor is using (node v8.15.1)... you might not have meteor installed though.

The idea to remove node-gyp was found here: https://github.com/nodejs/node-gyp/issues/809

My goal is to execute `npm run lint` on a project I checked out from github but it seems to be failing with what looks like another error now  (so I will continue to investigate):


_~/Workspace/reaction-platform/reaction$ npm run lint

> reaction@2.0.0-rc.11 lint /home/user/Workspace/reaction-platform/reaction
> eslint .

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
**TypeError: Cannot read property 'type' of null**
Occurred while linting /home/user/Workspace/reaction-platform/reaction/imports/plugins/core/payments/client/settings/settings.js:36
_

**Comment by karina-y** [comment]
i ran into this same issue after updating my ubuntu from 18.0.4 to 20, failing on fibers 2.0.0 when running 'npm install --production' on a build
i was able to get a successful installation with npm 5.6.0 and node 10.0.0
